
import { Language } from "./types";

export const DEFAULT_EVENT = {
  id: "",
  eventName: "",
  organizerEmail: "",
  budget: "20",
  exchangeDate: "",
  drawDate: "",
  message: "Ho ho ho! Time for gifts!",
};

export const DICTIONARY: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "Secret Santa Organizer",
    "nav.dashboard": "Dashboard",
    "nav.setup": "Settings",
    "nav.participants": "Elves",
    "nav.draw": "Draw",
    "nav.share": "Share",
    
    "landing.title": "Organize the Best Secret Santa",
    "landing.subtitle": "Create an event, invite friends, and let the magic happen.",
    "landing.btn": "Create New Event",
    "landing.join": "Have a ticket code?",

    "create.title": "Create Your Event",
    "create.btn": "Create Event & Get Link",
    "setup.title": "Event Settings",
    "setup.name": "Event Name",
    "setup.org_email": "Organizer Email",
    "setup.org_email_hint": "We'll send the management link here.",
    "setup.budget": "Budget / Limit",
    "setup.date": "Exchange Date",
    "setup.draw_date": "Draw Date",
    "setup.message": "Custom Message",
    
    "created.title": "Event Created Successfully!",
    "created.desc": "You are the organizer. Save this link to manage your event later.",
    "created.link_label": "Your Management Link",
    "created.email_btn": "Email this to me",
    "created.dashboard_btn": "Go to Dashboard",
    "created.qr_label": "Scan to Manage on Mobile",

    "part.title": "Manage Participants",
    "part.add": "Add Participant",
    "part.import": "Import Ticket",
    "part.import_csv": "Import CSV",
    "part.count": "Participants",
    "part.invite_link": "Invite Link",
    "part.invite_desc": "Share this link so people can join themselves.",
    "part.name": "Name",
    "part.email": "Email",
    "part.group": "Exclusion Group (Optional)",
    "part.dept": "Department",
    "part.wish": "Wishlist",
    
    "draw.title": "Draw Names",
    "draw.btn": "Start The Magic",
    "draw.retry": "Retry Draw",
    "draw.success": "Pairing Successful!",
    "draw.fail": "Could not satisfy constraints. Please check exclusion groups.",
    
    "share.title": "Distribute & Preview",
    "share.preview_as": "Preview as...",
    "share.reveal": "Reveal My Receiver",
    "share.copy": "Copy Message",
    "share.email": "Send Email",
    
    "join.title": "Join Secret Santa",
    "join.desc": "Enter your details to generate a ticket code. Send this code to the organizer.",
    "join.generate": "Generate Ticket",
    "join.code_label": "Your Ticket Code (Click to Copy)",
    "join.copied": "Copied!",
  },
  fr: {
    "app.title": "Organisateur Père Noël Secret",
    "nav.dashboard": "Tableau de bord",
    "nav.setup": "Paramètres",
    "nav.participants": "Lutins",
    "nav.draw": "Tirage",
    "nav.share": "Partage",
    
    "landing.title": "Organisez le meilleur Noël",
    "landing.subtitle": "Créez un événement, invitez des amis et laissez la magie opérer.",
    "landing.btn": "Créer un événement",
    "landing.join": "Vous avez un code ?",

    "create.title": "Créer votre événement",
    "create.btn": "Créer et obtenir le lien",
    "setup.title": "Paramètres",
    "setup.name": "Nom de l'événement",
    "setup.org_email": "Email de l'organisateur",
    "setup.org_email_hint": "Nous enverrons le lien de gestion ici.",
    "setup.budget": "Budget",
    "setup.date": "Date de l'échange",
    "setup.draw_date": "Date du tirage",
    "setup.message": "Message personnalisé",

    "created.title": "Événement créé avec succès !",
    "created.desc": "Vous êtes l'organisateur. Sauvegardez ce lien pour gérer l'événement.",
    "created.link_label": "Votre lien de gestion",
    "created.email_btn": "Me l'envoyer par email",
    "created.dashboard_btn": "Aller au tableau de bord",
    "created.qr_label": "Scanner pour gérer",

    "part.title": "Gérer les participants",
    "part.add": "Ajouter",
    "part.import": "Importer Billet",
    "part.import_csv": "Importer CSV",
    "part.count": "Participants",
    "part.invite_link": "Lien d'invitation",
    "part.invite_desc": "Partagez ce lien pour que les gens s'inscrivent.",
    "part.name": "Nom",
    "part.email": "Email",
    "part.group": "Groupe d'exclusion",
    "part.dept": "Département",
    "part.wish": "Liste de souhaits",
    
    "draw.title": "Tirage au sort",
    "draw.btn": "Lancer la magie",
    "draw.retry": "Réessayer",
    "draw.success": "Tirage réussi !",
    "draw.fail": "Impossible de satisfaire les contraintes.",
    
    "share.title": "Distribuer & Aperçu",
    "share.preview_as": "Aperçu en tant que...",
    "share.reveal": "Révéler ma cible",
    "share.copy": "Copier Message",
    "share.email": "Envoyer Email",
    
    "join.title": "Rejoindre",
    "join.desc": "Entrez vos détails pour générer un billet.",
    "join.generate": "Générer Billet",
    "join.code_label": "Votre Code Billet",
    "join.copied": "Copié !",
  },
  es: {
    "app.title": "Amigo Invisible",
    "nav.dashboard": "Panel",
    "nav.setup": "Ajustes",
    "nav.participants": "Elfos",
    "nav.draw": "Sorteo",
    "nav.share": "Compartir",

    "landing.title": "Organiza el mejor Amigo Invisible",
    "landing.subtitle": "Crea un evento, invita amigos y deja que ocurra la magia.",
    "landing.btn": "Crear Nuevo Evento",
    "landing.join": "¿Tienes un código?",

    "create.title": "Crea tu Evento",
    "create.btn": "Crear y Obtener Enlace",
    "setup.title": "Ajustes",
    "setup.name": "Nombre del Evento",
    "setup.org_email": "Email del Organizador",
    "setup.org_email_hint": "Enviaremos el enlace de gestión aquí.",
    "setup.budget": "Presupuesto",
    "setup.date": "Fecha de Intercambio",
    "setup.draw_date": "Fecha del Sorteo",
    "setup.message": "Mensaje Personalizado",

    "created.title": "¡Evento Creado con Éxito!",
    "created.desc": "Eres el organizador. Guarda este enlace para gestionar tu evento.",
    "created.link_label": "Tu Enlace de Gestión",
    "created.email_btn": "Enviármelo por email",
    "created.dashboard_btn": "Ir al Panel",
    "created.qr_label": "Escanear para gestionar",

    "part.title": "Gestionar Participantes",
    "part.add": "Añadir",
    "part.import": "Importar Ticket",
    "part.import_csv": "Importar CSV",
    "part.count": "Participantes",
    "part.invite_link": "Enlace de Invitación",
    "part.invite_desc": "Comparte esto para que la gente se una.",
    "part.name": "Nombre",
    "part.email": "Email",
    "part.group": "Grupo de Exclusión",
    "part.dept": "Departamento",
    "part.wish": "Lista de deseos",
    
    "draw.title": "Sorteo",
    "draw.btn": "Iniciar la Magia",
    "draw.retry": "Reintentar",
    "draw.success": "¡Emparejamiento Exitoso!",
    "draw.fail": "No se pudieron satisfacer las restricciones.",
    
    "share.title": "Distribuir y Vista Previa",
    "share.preview_as": "Vista previa como...",
    "share.reveal": "Revelar mi Amigo",
    "share.copy": "Copiar Mensaje",
    "share.email": "Enviar Email",
    
    "join.title": "Unirse",
    "join.desc": "Introduce tus datos para generar un ticket.",
    "join.generate": "Generar Ticket",
    "join.code_label": "Tu Código de Ticket",
    "join.copied": "¡Copiado!",
  },
};
